FROM fbiete/centos_epel:7
MAINTAINER Francisco Miguel Biete <fbiete@gmail.com>

RUN yum clean all \
&& yum install -y \
java-1.7.0-openjdk \
java-1.7.0-openjdk-devel \
java-1.7.0-openjdk-headless \
&& yum clean all