FROM centos:7
MAINTAINER Francisco Miguel Biete <fbiete@gmail.com>

RUN yum install -y \
epel-release \
&& yum clean all

RUN locale-gen es_ES.UTF-8 

ENV LANG es_ES.UTF-8  
ENV LANGUAGE es_ES.UTF-8
ENV LC_ALL es_ES.UTF-8
